import { describe, expect, it } from "vitest";
import { buildGraphResponse } from "@/lib/graph/graph-builder";
import { sanitizeGraphResponse } from "@/lib/graph/response-sanitizer";
import {
  formatStaticGraphSnapshotContractIssue,
  validateStaticGraphSnapshotContract
} from "@/lib/graph/static-graph-snapshot-contract.mjs";
import { yc2026GraphDataset } from "@/lib/graph/yc-spring-2026-dataset";
import type { TopVoiceAudienceId } from "@/lib/graph/types";

const VALIDATION_NOW = new Date("2026-07-16T12:00:00.000Z");
const MISMATCHED_PLATFORM_WEIGHT_CASES = [
  { platform: "x", configuredWeight: 0.24, canonicalWeight: 0.21 },
  { platform: "instagram", configuredWeight: 0.18, canonicalWeight: 0.21 },
  { platform: "linkedin", configuredWeight: 0.16, canonicalWeight: 0.15 },
  { platform: "github", configuredWeight: 0.14, canonicalWeight: 0.15 },
  { platform: "youtube", configuredWeight: 0.11, canonicalWeight: 0.1 },
  { platform: "product_hunt", configuredWeight: 0.08, canonicalWeight: 0.07 },
  { platform: "hacker_news", configuredWeight: 0.06, canonicalWeight: 0.05 },
  { platform: "reddit", configuredWeight: 0.03, canonicalWeight: 0.04 },
  { platform: "bilibili", configuredWeight: 0.01, canonicalWeight: 0.02 }
] as const;

describe("canonical v4 static graph snapshot contract", () => {
  it("accepts all nine graph variants generated by the current v4 builder", () => {
    const batchSlugs = ["S2026", "S26", "A16ZSR006"];
    const audiences: TopVoiceAudienceId[] = ["off", "yc_partners", "insiders"];

    for (const batchSlug of batchSlugs) {
      for (const topVoices of audiences) {
        const graph = sanitizeGraphResponse(
          buildGraphResponse({ batchSlug, topVoices }, yc2026GraphDataset)
        );
        const result = validateStaticGraphSnapshotContract(graph);
        const detail = result.ok
          ? ""
          : result.issues.slice(0, 3).map(formatStaticGraphSnapshotContractIssue).join("; ");

        expect(result, `${batchSlug}/${topVoices}: ${detail}`).toEqual({ ok: true, issues: [] });
      }
    }
  });

  it("accepts a complete minimal snapshot", () => {
    expect(
      validateStaticGraphSnapshotContract(validSnapshot(), {
        now: VALIDATION_NOW,
        maxFutureSkewMs: 0
      })
    ).toEqual({ ok: true, issues: [] });
  });

  it.each(MISMATCHED_PLATFORM_WEIGHT_CASES)(
    "rejects configured weight drift for $platform",
    ({ platform, configuredWeight, canonicalWeight }) => {
      const graph = validSnapshot();
      graph.nodes[0]!.scoreBreakdown.weightedPlatforms[0]!.platform = platform;
      graph.nodes[0]!.scoreBreakdown.weightedPlatforms[0]!.configuredWeight = configuredWeight;
      graph.nodes[0]!.topPlatform = platform;
      graph.leaderboard[0]!.topPlatform = platform;

      const result = validateStaticGraphSnapshotContract(graph, {
        now: VALIDATION_NOW,
        maxFutureSkewMs: 0
      });

      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.issues).toContainEqual({
          path: "nodes[0].scoreBreakdown.weightedPlatforms[0].configuredWeight",
          message: `must equal canonical v4 weight ${canonicalWeight} for ${platform}`
        });
      }
    }
  );

  it("accepts a filtered Top Voice snapshot with canonical score state and full-cohort rank gaps", () => {
    const graph = validSnapshot();
    graph.selectedTopVoiceAudience.id = "insiders";
    Object.assign(graph.nodes[0]!, {
      selectedTopVoiceAudience: { id: "insiders" },
      topVoiceConnectionCount: 1
    });
    Object.assign(graph.evidence[0]!, {
      topVoice: {
        audienceId: "insiders",
        originalContributionScore: graph.evidence[0]!.contributionScore
      }
    });
    graph.leaderboard[0]!.rank = 3;
    graph.fastestGaining[0]!.rank = 4;
    graph.fastestGaining[0]!.dod.currentRank = 3;
    graph.fastestGaining[0]!.wow.currentRank = 3;

    expect(
      validateStaticGraphSnapshotContract(graph, {
        now: VALIDATION_NOW,
        maxFutureSkewMs: 0
      })
    ).toEqual({ ok: true, issues: [] });
  });

  it("accepts explicit null account lineage without a materialized account", () => {
    const graph = validSnapshot();
    graph.evidence[0]!.socialAccountId = null;
    graph.nodes[0]!.socialAccounts = [];

    expect(
      validateStaticGraphSnapshotContract(graph, {
        now: VALIDATION_NOW,
        maxFutureSkewMs: 0
      })
    ).toEqual({ ok: true, issues: [] });
  });

  it.each([
    {
      name: "dangling account lineage",
      path: "evidence[0].socialAccountId",
      mutate: (graph: ValidSnapshot) => {
        graph.evidence[0]!.socialAccountId = materializedSocialAccountId(
          "company",
          "company-1",
          "x",
          "https://x.com/missing"
        );
      }
    },
    {
      name: "wrong-owner account lineage",
      path: "evidence[0].socialAccountId",
      mutate: (graph: ValidSnapshot) => {
        const account = fixtureSocialAccount(
          "founder",
          "founder-1",
          "x",
          "https://x.com/founderone"
        );
        graph.nodes[0]!.socialAccounts = [];
        graph.nodes[0]!.founders.push({ id: "founder-1", socialAccounts: [account] });
        graph.evidence[0]!.socialAccountId = account.id;
      }
    },
    {
      name: "wrong-platform account lineage",
      path: "evidence[0].socialAccountId",
      mutate: (graph: ValidSnapshot) => {
        const account = fixtureSocialAccount(
          "company",
          "company-1",
          "github",
          "https://github.com/companyone"
        );
        graph.nodes[0]!.socialAccounts = [account];
        graph.evidence[0]!.socialAccountId = account.id;
      }
    },
    {
      name: "materialized account ID collision",
      path: "nodes[0].socialAccounts[1].id",
      mutate: (graph: ValidSnapshot) => {
        graph.nodes[0]!.socialAccounts.push(
          structuredClone(graph.nodes[0]!.socialAccounts[0]!)
        );
      }
    },
    {
      name: "fabricated account ID",
      path: "nodes[0].socialAccounts[0].id",
      mutate: (graph: ValidSnapshot) => {
        graph.nodes[0]!.socialAccounts[0]!.id = "fabricated-account-id";
        graph.evidence[0]!.socialAccountId = "fabricated-account-id";
      }
    }
  ])("rejects $name", ({ path, mutate }) => {
    const graph = validSnapshot();
    mutate(graph);

    const result = validateStaticGraphSnapshotContract(graph, {
      now: VALIDATION_NOW,
      maxFutureSkewMs: 0
    });

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.issues.some((issue) => issue.path === path), JSON.stringify(result.issues)).toBe(true);
    }
  });

  it.each([
    {
      name: "out-of-range node score",
      path: "nodes[0].score",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.score = 101; }
    },
    {
      name: "node and total score mismatch",
      path: "nodes[0].score",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.totalScore = 63; }
    },
    {
      name: "out-of-range absolute score",
      path: "nodes[0].scoreBreakdown.absoluteScore",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.absoluteScore = -1; }
    },
    {
      name: "out-of-range calibration input",
      path: "nodes[0].scoreBreakdown.calibration.inputScore",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.calibration.inputScore = 101; }
    },
    {
      name: "out-of-range calibration percentile",
      path: "nodes[0].scoreBreakdown.calibration.percentile",
      mutate: (graph: ValidSnapshot) => {
        (graph.nodes[0]!.scoreBreakdown.calibration as { percentile: number | null }).percentile = 1.1;
      }
    },
    {
      name: "out-of-range platform score",
      path: "nodes[0].scoreBreakdown.platformScores.x",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.platformScores.x = 101; }
    },
    {
      name: "out-of-range evidence score",
      path: "evidence[0].contributionScore",
      mutate: (graph: ValidSnapshot) => { graph.evidence[0]!.contributionScore = 101; }
    },
    {
      name: "rejected positive evidence",
      path: "evidence[0].review_state",
      mutate: (graph: ValidSnapshot) => { graph.evidence[0]!.review_state = "rejected"; }
    },
    {
      name: "unscored positive evidence",
      path: "evidence[0].tractionStatus",
      mutate: (graph: ValidSnapshot) => { graph.evidence[0]!.tractionStatus = "unscored"; }
    },
    {
      name: "explicitly noneligible positive evidence",
      path: "evidence[0]",
      mutate: (graph: ValidSnapshot) => { graph.evidence[0]!.score_eligible = false; }
    },
    {
      name: "dated confidence count above scored count",
      path: "nodes[0].scoreBreakdown.confidence.datedEvidenceCount",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.confidence.datedEvidenceCount = 2; }
    },
    {
      name: "verified confidence count above scored count",
      path: "nodes[0].scoreBreakdown.confidence.verifiedLinkCount",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.confidence.verifiedLinkCount = 2; }
    },
    {
      name: "scored confidence count above referenced evidence",
      path: "nodes[0].scoreBreakdown.confidence.scoredEvidenceCount",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.scoreBreakdown.confidence.scoredEvidenceCount = 2; }
    },
    {
      name: "leaderboard and node score mismatch",
      path: "leaderboard[0].score",
      mutate: (graph: ValidSnapshot) => { graph.leaderboard[0]!.score = 62; }
    },
    {
      name: "future snapshot timestamps",
      path: "generatedAt",
      mutate: (graph: ValidSnapshot) => {
        graph.generatedAt = "2026-07-16T12:00:01.000Z";
        graph.scoringContext.responseBuiltAt = graph.generatedAt;
      }
    },
    {
      name: "response build time drift",
      path: "scoringContext.responseBuiltAt",
      mutate: (graph: ValidSnapshot) => {
        graph.scoringContext.responseBuiltAt = "2026-07-16T05:00:01.000Z";
      }
    },
    {
      name: "future evidence publication time",
      path: "evidence[0].postedAt",
      mutate: (graph: ValidSnapshot) => {
        graph.evidence[0]!.postedAt = "2026-07-16T05:00:01.000Z";
      }
    },
    {
      name: "audience and scoring scope drift",
      path: "scoringContext.scoreScope",
      mutate: (graph: ValidSnapshot) => { graph.scoringContext.scoreScope = "top_voice"; }
    },
    {
      name: "selected platform scoring context drift",
      path: "scoringContext.selectedPlatforms",
      mutate: (graph: ValidSnapshot) => { graph.scoringContext.selectedPlatforms = ["x"]; }
    },
    {
      name: "Top Voice member-weighted evidence",
      path: "evidence[0].contributionScore",
      mutate: (graph: ValidSnapshot) => {
        Object.assign(graph.evidence[0]!, {
          contributionScore: 80,
          topVoice: { audienceId: "insiders", originalContributionScore: 64 }
        });
      }
    },
    {
      name: "incoherent node identity",
      path: "nodes[0].id",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.id = "company:somebody-else"; }
    },
    {
      name: "node outside the batch scope",
      path: "nodes[0].batchSlug",
      mutate: (graph: ValidSnapshot) => { graph.nodes[0]!.batchSlug = "S26"; }
    },
    {
      name: "edge with a missing endpoint",
      path: "edges[0].target",
      mutate: (graph: ValidSnapshot) => {
        graphWithEdges(graph).edges = [{
          id: "edge-1",
          source: "company:company-1",
          target: "company:missing",
          edgeType: "industry_similarity",
          weight: 0.5,
          label: "Industry similarity",
          explanation: "Fixture edge."
        }];
      }
    },
    {
      name: "ordinal rank for a tied score",
      path: "leaderboard[1].rank",
      mutate: (graph: ValidSnapshot) => {
        addTiedCompany(graph);
        graph.leaderboard[1]!.rank = 2;
      }
    },
    {
      name: "momentum row identity drift",
      path: "fastestGaining[0].companyId",
      mutate: (graph: ValidSnapshot) => { graph.fastestGaining[0]!.companyId = "company-missing"; }
    },
    {
      name: "momentum current score drift",
      path: "fastestGaining[0].dod.currentScore",
      mutate: (graph: ValidSnapshot) => { graph.fastestGaining[0]!.dod.currentScore = 63; }
    },
    {
      name: "momentum current tied-rank drift",
      path: "fastestGaining[1].wow.currentRank",
      mutate: (graph: ValidSnapshot) => {
        addTiedCompany(graph);
        graph.fastestGaining[1]!.wow.currentRank = 2;
      }
    },
    {
      name: "half-null momentum baseline",
      path: "fastestGaining[0].dod.baselineRank",
      mutate: (graph: ValidSnapshot) => { graph.fastestGaining[0]!.dod.baselineRank = 2; }
    },
    {
      name: "nonzero delta without a baseline",
      path: "fastestGaining[0].dod.scoreDelta",
      mutate: (graph: ValidSnapshot) => { graph.fastestGaining[0]!.dod.scoreDelta = 1; }
    },
    {
      name: "incorrect score delta",
      path: "fastestGaining[0].dod.scoreDelta",
      mutate: (graph: ValidSnapshot) => {
        Object.assign(graph.fastestGaining[0]!.dod, {
          baselineScore: 60,
          baselineRank: 2,
          scoreDelta: 3,
          percentDelta: 6.7,
          rankDelta: 1
        });
      }
    },
    {
      name: "incorrect percent delta",
      path: "fastestGaining[0].dod.percentDelta",
      mutate: (graph: ValidSnapshot) => {
        Object.assign(graph.fastestGaining[0]!.dod, {
          baselineScore: 60,
          baselineRank: 2,
          scoreDelta: 4,
          percentDelta: 7,
          rankDelta: 1
        });
      }
    },
    {
      name: "incorrect rank delta",
      path: "fastestGaining[0].dod.rankDelta",
      mutate: (graph: ValidSnapshot) => {
        Object.assign(graph.fastestGaining[0]!.dod, {
          baselineScore: 60,
          baselineRank: 2,
          scoreDelta: 4,
          percentDelta: 6.7,
          rankDelta: 0
        });
      }
    },
    {
      name: "future benchmark timestamp",
      path: "fastestGaining[0].dod.benchmarkedAt",
      mutate: (graph: ValidSnapshot) => {
        graph.fastestGaining[0]!.dod.benchmarkedAt = "2026-07-16T05:00:01.000Z";
      }
    }
  ])("rejects $name", ({ path, mutate }) => {
    const graph = validSnapshot();
    mutate(graph);

    const result = validateStaticGraphSnapshotContract(graph, {
      now: VALIDATION_NOW,
      maxFutureSkewMs: 0
    });

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.issues.some((issue) => issue.path === path), JSON.stringify(result.issues)).toBe(true);
    }
  });
});

function validSnapshot() {
  const socialAccount = fixtureSocialAccount(
    "company",
    "company-1",
    "x",
    "https://x.com/companyone"
  );
  const evidence = {
    id: "evidence-1",
    entityType: "company",
    entityId: "company-1",
    platform: "x",
    authorName: "Company One",
    authorHandle: "companyone",
    postedAt: "2026-07-16T05:00:00.000Z",
    publishedAtPrecision: "exact",
    text: "Company One traction update",
    mediaType: "text",
    metrics: { views: 1_000 },
    contributionScore: 64,
    normalizedScore: 64,
    tractionStatus: "scored",
    score_eligible: true,
    sourceUrl: "https://x.com/companyone/status/1",
    why: "Canonical v4 fixture.",
    attachedCompanyId: "company-1",
    socialAccountId: socialAccount.id as string | null,
    review_state: "verified",
    linkStatus: "verified"
  };
  const scoreBreakdown = {
    modelId: "returner-traction",
    modelVersion: "4.1.0",
    modelName: "returner-traction-v4-absolute-fixed-platform",
    totalScore: 13,
    absoluteScore: 13,
    weightedAvailableScore: 64,
    coverageFactor: 0.21,
    platformsWithEvidence: 1,
    totalSupportedPlatforms: 9,
    platformScores: { x: 64 },
    weightedPlatforms: [{
      platform: "x",
      score: 64,
      configuredWeight: 0.21,
      appliedWeight: 0.21,
      contribution: 13.44,
      evidenceCount: 1
    }],
    signalFamilyScores: {
      reach: 64,
      engagement: 0,
      developerAdoption: 0,
      launchAndCommunity: 0,
      momentum: 64
    },
    confidence: {
      level: "medium",
      value: 0.5,
      reasons: ["One scored row."],
      scoredEvidenceCount: 1,
      datedEvidenceCount: 1,
      verifiedLinkCount: 1
    },
    calibration: {
      method: "none",
      cohortSize: 1,
      percentile: null,
      inputScore: 13
    },
    limitations: [],
    evidenceAsOf: "2026-07-16T05:00:00.000Z",
    explanation: "Canonical v4 fixture."
  };
  const node = {
    id: "company:company-1",
    entityType: "company",
    entityId: "company-1",
    label: "Company One",
    batchSlug: "S2026",
    score: 13,
    topPlatform: "x",
    platformScores: { x: 64 },
    scoreBreakdown,
    socialAccounts: [socialAccount],
    evidenceIds: [evidence.id],
    relatedEntityIds: [],
    founders: [] as FixtureFounder[]
  };

  return {
    batch: { slug: "S2026", companyCountObserved: 1 },
    batches: [{ slug: "S2026" }],
    nodes: [node],
    edges: [],
    leaderboard: [{
      rank: 1,
      companyId: "company-1",
      companyName: "Company One",
      score: 13,
      topPlatform: "x",
      biggestContribution: evidence
    }],
    fastestGaining: [{
      rank: 1,
      companyId: "company-1",
      companyName: "Company One",
      dod: momentum(13, 1),
      wow: momentum(13, 1)
    }],
    needsReview: [],
    evidence: [evidence],
    platformStatus: [],
    selectedTopVoiceAudience: { id: "off" },
    topVoiceAudiences: [],
    generatedAt: "2026-07-16T05:00:00.000Z",
    scoringContext: {
      modelId: "returner-traction",
      modelVersion: "4.1.0",
      modelName: "returner-traction-v4-absolute-fixed-platform",
      scoreScope: "all_platforms",
      selectedPlatforms: [] as string[],
      responseBuiltAt: "2026-07-16T05:00:00.000Z",
      evidenceAsOf: "2026-07-16T05:00:00.000Z"
    },
    mode: "official_snapshot"
  };
}

function momentum(currentScore: number, currentRank: number) {
  return {
    scoreDelta: 0,
    percentDelta: 0,
    rankDelta: 0,
    currentScore,
    currentRank,
    baselineScore: null as number | null,
    baselineRank: null as number | null,
    benchmarkedAt: null as string | null
  };
}

function addTiedCompany(graph: ValidSnapshot) {
  const evidence = structuredClone(graph.evidence[0]!);
  const socialAccount = fixtureSocialAccount(
    "company",
    "company-2",
    "x",
    "https://x.com/companytwo"
  );
  evidence.id = "evidence-2";
  evidence.entityId = "company-2";
  evidence.attachedCompanyId = "company-2";
  evidence.authorName = "Company Two";
  evidence.authorHandle = "companytwo";
  evidence.sourceUrl = "https://x.com/companytwo/status/2";
  evidence.socialAccountId = socialAccount.id;

  const node = structuredClone(graph.nodes[0]!);
  node.id = "company:company-2";
  node.entityId = "company-2";
  node.label = "Company Two";
  node.socialAccounts = [socialAccount];
  node.evidenceIds = [evidence.id];

  graph.batch.companyCountObserved = 2;
  graph.evidence.push(evidence);
  graph.nodes.push(node);
  graph.leaderboard.push({
    rank: 1,
    companyId: "company-2",
    companyName: "Company Two",
    score: 13,
    topPlatform: "x",
    biggestContribution: evidence
  });
  graph.fastestGaining.push({
    rank: 2,
    companyId: "company-2",
    companyName: "Company Two",
    dod: momentum(13, 1),
    wow: momentum(13, 1)
  });
}

function graphWithEdges(graph: ValidSnapshot) {
  return graph as unknown as {
    edges: Array<{
      id: string;
      source: string;
      target: string;
      edgeType: string;
      weight: number;
      label: string;
      explanation: string;
    }>;
  };
}

function fixtureSocialAccount(
  entityType: "company" | "founder",
  entityId: string,
  platform: string,
  url: string
) {
  return {
    id: materializedSocialAccountId(entityType, entityId, platform, url),
    platform,
    handle: url.split("/").at(-1) ?? null,
    url,
    review_state: "verified" as const,
    discoveredFromUrl: null,
    matchReason: "Canonical lineage fixture."
  };
}

function materializedSocialAccountId(
  entityType: "company" | "founder",
  entityId: string,
  platform: string,
  canonicalUrl: string
) {
  return `acct:${entityType}:${entityId}:${platform}:${encodeURIComponent(canonicalUrl)}`;
}

type FixtureSocialAccount = ReturnType<typeof fixtureSocialAccount>;
type FixtureFounder = { id: string; socialAccounts: FixtureSocialAccount[] };

type ValidSnapshot = ReturnType<typeof validSnapshot>;
