import { load } from "cheerio";
import { isIP } from "node:net";
import { DASHBOARD_WINDOW_MS, type DashboardCandidate } from "./contracts";
import { canonicalDashboardUrl, compactSentence, compactWhitespace, safeDate, stableHash } from "./normalization";
import { isDashboardCandidateEligible } from "./pipeline";

const MAX_RESPONSE_BYTES = 1_500_000;
// HN is useful as lightweight corroboration, but it is intentionally a small
// input lane. The publication layer owns the final story-level share cap;
// retaining this bounded cohort here lets matching editorial coverage cluster
// with the correct discussion instead of manufacturing a singleton baseline.
const MAX_HN_ITEMS = 12;
const MIN_HN_UPVOTES = 20;
const MIN_HN_COMMENTS = 5;
const MAX_GITHUB_ITEMS = 40;
const MIN_GITHUB_STARS = 100;
const MAX_GITHUB_EVENT_ITEMS = 100;
const X_RECENT_SEARCH_ENDPOINT = "https://api.x.com/2/tweets/search/recent";
const MAX_X_RECENT_SEARCH_ITEMS = 100;
const MAX_YOUTUBE_RESPONSE_BYTES = 1_750_000;
const MAX_YOUTUBE_PLAYER_RESPONSE_BYTES = 750_000;
const MAX_YOUTUBE_DETAIL_CANDIDATES_PER_CHANNEL = 2;
const MAX_CONCURRENT_YOUTUBE_CHANNELS = 4;
// This is a public Innertube protocol identifier, not a credential. YouTube's
// no-key WEB browse/player endpoints accept older client versions, which lets
// the worker avoid extracting and retaining a page-embedded API key.
const YOUTUBE_WEB_CLIENT_VERSION = "2.20240101.00.00";
export const MAX_DASHBOARD_YOUTUBE_CHANNELS = 20;
const MAX_RSS_ITEMS_PER_FEED = 40;
// Primary research is a direct, high-quality lane rather than a broad
// consumer feed. Keep its discovery window modestly wider so the Top 100 can
// remain substantive without re-admitting reviews, deals, or lifestyle cards.
const MAX_RESEARCH_ITEMS_PER_FEED = 60;
const MAX_REDDIT_ITEMS_PER_SUBREDDIT = 40;
const MAX_ENTRY_IMAGE_HTML_CHARS = 32_000;
const MIN_RSS_SUMMARY_WORDS = 8;

// Publisher feeds can contain adjacent science, culture, or general-interest
// reporting. A source name is not a relevance guarantee: a card must lead
// with a concrete technology signal in its headline. Descriptions may
// corroborate applied-tech reporting, but can never qualify a story by
// themselves (RSS summaries often include unrelated site-wide boilerplate).
const CORE_TECHNOLOGY_SIGNAL = new RegExp([
  "\\btechnology\\b", "\\bai\\b", "a\\.i\\.", "artificial intelligence", "machine learning", "generative", "large language model", "\\bllm\\b", "agentic", "chatbot", "algorithm", "model training",
  "\\bsoftware\\b", "open[ -]?source", "developer", "development", "program(?:ming|mer)", "coding", "codebase", "compiler", "\\bapi\\b", "\\bapp(?:lication)?\\b", "app store", "operating system", "\\b(?:ios|macos|linux|android|windows)\\b", "deployment",
  "\\bcloud\\b", "\\bserver\\b", "\\bdatabase\\b", "data centers?", "data storage", "data set", "\\bcompute\\b", "computing", "supercomputer", "semiconductor", "\\bchips?\\b", "\\bgpu\\b", "processor", "hardware", "firmware", "electronics?", "signal processing", "\\bantenna\\b", "\\busb(?:4|[- ]?c)?\\b",
  "\\binternet\\b", "\\bweb\\b", "browser", "digital platform", "network(?:ing)?", "telecom", "wireless", "broadband", "\\b(?:5g|6g|wi-?fi)\\b", "\\bnpm\\b", "\\bplugins?\\b",
  "cyber(?:security)?", "\\bsecurity\\b", "privacy", "encryption", "ransomware", "malware", "spyware", "phishing", "hack(?:er|ed|ing)?", "vulnerabilit(?:y|ies)", "prompt injection",
  "\\bstartup\\b", "fund(?:ing|raise)", "venture capital", "\\bvc\\b", "fintech", "payment(?:s)?", "\\bipo\\b", "cloud storage",
  "robot(?:ics)?", "autonomous", "self-driving", "electric vehicle", "\\bev\\b", "\\bbattery\\b", "energy grid", "biotech", "bio(?:tech|engineering)", "genom(?:e|ics)", "medical device", "\\bquantum\\b", "climate tech", "carbon capture", "facial recognition", "watermark(?:ing)?", "\\b(?:iphone|smartphone|mobile)\\b",
  "\\b(?:openai|anthropic|nvidia|amd|intel|tesla|tsmc|neuralink)\\b"
].join("|"), "i");

// These areas can be technology reporting, but their terms alone are too
// broad: a solar eclipse, an arms-control story, or a rocket launch should
// not occupy an editorial-tech slot. They need an explicit core-tech context.
const APPLIED_TECHNOLOGY_TITLE_SIGNAL = new RegExp([
  "\\bsolar\\b", "wind power", "\\bnuclear\\b", "\\bfusion\\b", "electric aircraft", "\\baircraft\\b", "aviation", "aerospace",
  "\\bdrone\\b", "spacecraft", "spaceflight", "satellite", "\\brocket\\b", "orbit(?:al)?"
].join("|"), "i");

const GEOPOLITICAL_OR_MILITARY_SIGNAL = new RegExp([
  "\\b(?:war|warfare|military|navy|missile|atomic arms)\\b", "\\b(?:ukraine|russia|russian)\\b.*\\b(?:rocket|factory|weapons?)\\b"
].join("|"), "i");

const RSS_PUBLISHER_BOILERPLATE = /ScienceAlert stories are written,\s*fact-checked,\s*and edited by humans,\s*never generated by AI\.?/gi;

const COMMERCE_PROMOTION_FORMAT = new RegExp([
  "\\bdeals?\\b", "\\bsale\\b", "\\bdiscount\\b", "\\bpromo(?:tion| code)?\\b", "\\bcoupon\\b", "\\bgiveaway\\b", "giving away", "for free", "\\bshopping\\b", "shop now", "buy now", "available to buy", "\\bsponsored\\b", "save\\s+\\$", "under\\s+\\$", "%\\s*off", "lifetime access", "\\bupgrade deal\\b", "upgrade your (?:pc|computer|laptop|phone|device)", "pay\\s+\\$\\d", "plan for\\s+\\$\\d", "for just\\s+\\$\\d"
].join("|"), "i");

const LOWER_VALUE_EDITORIAL_FORMAT = new RegExp([
  "\\bbest\\b", "\\breviews?\\b", "\\bvs\\.?\\b", "\\bversus\\b", "\\bcomparison\\b", "hands-on", "\\bunboxing\\b", "\\b(?:i|we)\\s+(?:tested|reviewed)\\b",
  "\\bhow to\\b", "what(?:'s| is| are| happens)", "\\bexplained\\b", "\\bguides?\\b", "\\bapple loop\\b", "\\b(?:iphone|smartphone|laptop|macbook).{0,32}\\bprice\\b", "how much does it cost", "is it worth it"
].join("|"), "i");

const OPINION_OR_VAGUE_FORMAT = new RegExp([
  "\\bopinion\\b", "\\bcolumn\\b", "\\bessay\\b", "\\bmanifesto(?:s)?\\b", "\\bexplainer\\b", "\\bthe case for\\b", "\\bai\\s+vs\\b", "\\bsatir(?:e|ical)\\b", "\\bparody\\b", "\\bjoke\\b", "can['’]?t go viral", "\\bgo viral\\b", "moved the goalposts", "\\bapod\\b", "astronomy picture of the day", "\\bexpo\\b", "\\bairshow\\b", "this week in science", "will redefine",
  "prompt(?:s)?\\s+(?:injections?|injected).*\\b(?:legal|court|filing)s?\\b", "\\b(?:legal|court|filing)s?.*(?:prompt(?:s)?\\s+(?:injections?|injected)|injected\\s+prompts?)"
].join("|"), "i");

const ENTERTAINMENT_OR_LIFESTYLE_SIGNAL = new RegExp([
  "\\bmovies?\\b", "\\bfilms?\\b", "\\btelevision\\b", "\\btv\\b", "\\bseries\\b", "\\bseason\\b", "\\bepisode\\b", "\\btrailer\\b", "\\bcast\\b", "\\bactors?\\b", "\\bactress(?:es)?\\b", "\\bconcert\\b", "\\bmusic\\b", "\\bsongs?\\b", "\\balbum\\b", "\\bpodcast\\b", "\\bcelebrity\\b", "\\bhollywood\\b",
  "\\banime\\b", "\\bgames?\\b", "\\bgamer\\b", "\\bgaming\\b", "vibe coded", "video games?", "\\bplaystation\\b", "\\bxbox\\b", "\\bnintendo\\b", "\\bdisney\\b", "\\bmarvel\\b", "star wars", "\\bnetflix\\b", "\\bhbo\\b", "\\bhulu\\b", "\\btheat(?:er|re)\\b", "roleplay(?:ing)?", "have a laugh",
  "\\bnecklace\\b", "\\bjewelry\\b", "\\bfashion\\b", "\\bbeauty\\b", "\\bgarden\\b", "ice cream", "\\bfood\\b", "\\brecipe\\b", "\\bbooks?\\b", "secondhand", "\\bmushrooms?\\b", "\\bdating\\b", "\\brelationship\\b", "\\bparents?\\b", "\\bkids?\\b", "screen time", "\\bporn\\b", "\\bsexual\\b", "\\bmasturbation\\b", "\\binfluencers?\\b", "\\bfitness\\b", "bodybuild(?:er|ing)", "looksmaxx", "\\bsemaglutide\\b", "\\bglp[- ]?1s?\\b", "\\bdementia\\b", "mental health advice", "weight loss", "\\bdiet\\b",
  "\\bheadphones?\\b", "\\bearbuds?\\b", "watch bands?", "phone grip", "\\bturntable\\b", "bookshelf speakers?", "\\bspeakers?\\b", "\\bprinters?\\b", "\\bvacuum\\b", "\\bfan\\b", "sports betting"
].join("|"), "i");

const LOW_SIGNAL_OR_PROMOTIONAL_REPOSITORY = /\b(?:crypto(?:currency)?|nft|token|airdrop|coin|memecoin|web3|gambling|casino|betting|preset|gitbash|fake[ -]?balance|vibe[ -]?coding)\b/i;

// Environment configuration may select a feed path only on these public
// publication hosts. Keeping this list literal (rather than accepting an
// arbitrary public hostname) prevents the worker from becoming a general
// outbound-fetch proxy through DASHBOARD_RSS_FEEDS.
const CONFIGURED_RSS_HOST_ALLOWLIST = new Set([
  "www.technologyreview.com",
  "feeds.arstechnica.com",
  "techcrunch.com",
  "www.theverge.com",
  "www.wired.com",
  "spectrum.ieee.org",
  "venturebeat.com",
  "www.engadget.com",
  "www.theguardian.com",
  "rss.nytimes.com",
  "feeds.bbci.co.uk",
  "api.theregister.com",
  "news.mit.edu",
  "research.google",
  "huggingface.co",
  "www.cnet.com",
  "gizmodo.com",
  "www.zdnet.com",
  "www.pcmag.com",
  "mashable.com",
  "www.ft.com",
  "the-decoder.com",
  "thenewstack.io",
  "feed.infoq.com",
  "www.bleepingcomputer.com",
  "www.techspot.com",
  "www.tomshardware.com",
  "9to5google.com",
  "www.bloomberg.com",
  "www.geekwire.com",
  "therecord.media",
  "spacenews.com",
  "www.darkreading.com",
  "www.hpcwire.com",
  "phys.org",
  "www.datacenterdynamics.com",
  "themarkup.org",
  "restofworld.org",
  "krebsonsecurity.com",
  "www.securityweek.com",
  "lwn.net",
  "machinelearning.apple.com",
  "security.googleblog.com",
  "deepmind.google",
  "www.microsoft.com",
  "blog.cloudflare.com"
]);

/**
 * Public, read-only editorial feeds. These are intentionally direct publisher
 * feeds rather than a search-engine feed or a generic scrape: that keeps the
 * worker bounded, makes the source shown to visitors unambiguous, and gives
 * reporting and research a much larger discovery surface than discussions.
 */
export const DEFAULT_DASHBOARD_RSS_FEEDS = [
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/", quality: 84 },
  { name: "Ars Technica", url: "https://feeds.arstechnica.com/arstechnica/index", quality: 80 },
  { name: "IEEE Spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", quality: 84 },
  { name: "MIT News AI", url: "https://news.mit.edu/rss/topic/artificial-intelligence2", quality: 84 },
  { name: "The New York Times Technology", url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", quality: 84 },
  { name: "BBC News Technology", url: "https://feeds.bbci.co.uk/news/technology/rss.xml", quality: 82 },
  { name: "The Guardian Technology", url: "https://www.theguardian.com/uk/technology/rss", quality: 80 },
  { name: "WIRED", url: "https://www.wired.com/feed/rss", quality: 78 },
  { name: "The Verge", url: "https://www.theverge.com/rss/index.xml", quality: 76 },
  { name: "TechCrunch", url: "https://techcrunch.com/feed/", quality: 74 },
  { name: "VentureBeat", url: "https://venturebeat.com/feed/", quality: 72 },
  { name: "Engadget", url: "https://www.engadget.com/rss.xml", quality: 70 },
  { name: "The Register", url: "https://api.theregister.com/api/v1/article?orderBy=published&site_id=2&remapper=rss", quality: 72 },
  { name: "Google Research", url: "https://research.google/blog/rss/", quality: 82 },
  { name: "Hugging Face", url: "https://huggingface.co/blog/feed.xml", quality: 76 },
  { name: "CNET", url: "https://www.cnet.com/rss/news/", quality: 74 },
  { name: "Gizmodo", url: "https://gizmodo.com/feed", quality: 70 },
  { name: "ZDNET", url: "https://www.zdnet.com/news/rss.xml", quality: 74 },
  { name: "PCMag", url: "https://www.pcmag.com/feeds/rss/latest", quality: 74 },
  { name: "Mashable Tech", url: "https://mashable.com/feeds/rss/tech", quality: 70 },
  { name: "Financial Times Technology", url: "https://www.ft.com/technology?format=rss", quality: 84 },
  { name: "The Decoder", url: "https://the-decoder.com/feed/", quality: 80 },
  { name: "The New Stack", url: "https://thenewstack.io/feed/", quality: 80 },
  { name: "InfoQ", url: "https://feed.infoq.com/", quality: 80 },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/feed/", quality: 80 },
  { name: "TechSpot", url: "https://www.techspot.com/backend.xml", quality: 74 },
  { name: "Tom's Hardware", url: "https://www.tomshardware.com/feeds/all", quality: 74 },
  { name: "9to5Google", url: "https://9to5google.com/feed/", quality: 72, maxItems: 2 },
  { name: "Bloomberg Technology", url: "https://www.bloomberg.com/feeds/technology/news.rss", quality: 86 },
  { name: "GeekWire", url: "https://www.geekwire.com/feed/", quality: 80 },
  { name: "The Record", url: "https://therecord.media/feed", quality: 82 },
  { name: "SpaceNews", url: "https://spacenews.com/feed/", quality: 82 },
  { name: "Dark Reading", url: "https://www.darkreading.com/rss.xml", quality: 82 },
  { name: "HPCwire", url: "https://www.hpcwire.com/feed/", quality: 82 },
  { name: "Phys.org Technology", url: "https://phys.org/rss-feed/technology-news/", quality: 78 },
  { name: "Data Center Dynamics", url: "https://www.datacenterdynamics.com/en/rss/", quality: 82 },
  { name: "The Markup", url: "https://themarkup.org/feeds/rss.xml", quality: 84 },
  { name: "Rest of World", url: "https://restofworld.org/feed/latest/", quality: 82 },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/feed/", quality: 86 },
  { name: "SecurityWeek", url: "https://www.securityweek.com/feed/", quality: 80 },
  { name: "LWN.net", url: "https://lwn.net/headlines/rss", quality: 84 },
  { name: "Google Online Security", url: "https://security.googleblog.com/feeds/posts/default?alt=rss", quality: 82, maxItems: 3 },
  { name: "Google DeepMind", url: "https://deepmind.google/blog/rss.xml", quality: 82, maxItems: 3 },
  { name: "Microsoft Security", url: "https://www.microsoft.com/en-us/security/blog/feed/", quality: 78, maxItems: 2 },
  { name: "Cloudflare Blog", url: "https://blog.cloudflare.com/rss/", quality: 78, maxItems: 2 }
] as const;

/**
 * Papers are candidates only when another observed signal corroborates them.
 * The category feeds keep the worker broad across AI, ML, language, vision,
 * robotics, and security without issuing an unbounded research search.
 */
export const DEFAULT_DASHBOARD_RESEARCH_FEEDS = [
  { name: "arXiv cs.AI", url: "https://rss.arxiv.org/rss/cs.AI", quality: 84, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv cs.LG", url: "https://rss.arxiv.org/rss/cs.LG", quality: 84, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv stat.ML", url: "https://rss.arxiv.org/rss/stat.ML", quality: 84, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv cs.CL", url: "https://rss.arxiv.org/rss/cs.CL", quality: 82, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv cs.CV", url: "https://rss.arxiv.org/rss/cs.CV", quality: 82, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv cs.RO", url: "https://rss.arxiv.org/rss/cs.RO", quality: 82, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "arXiv cs.CR", url: "https://rss.arxiv.org/rss/cs.CR", quality: 80, platform: "research", sourceKind: "paper", independentlyReported: false },
  { name: "Apple Machine Learning Research", url: "https://machinelearning.apple.com/rss.xml", quality: 86, platform: "research", sourceKind: "paper", independentlyReported: false }
] as const satisfies readonly DashboardRssFeed[];

/** Fixed public communities avoid an unbounded Reddit search surface. */
export const DEFAULT_DASHBOARD_REDDIT_SUBREDDITS = ["MachineLearning", "technology", "programming", "startups"] as const;

/**
 * One relevance-sorted official-API request gives the strict Top 100 a broad
 * social discovery lane without turning the hourly worker into an unbounded
 * crawler. Eligibility still requires a native million-view reading below.
 */
export const DEFAULT_DASHBOARD_X_QUERY = [
  "(\"artificial intelligence\" OR ChatGPT OR Claude OR Gemini OR \"machine learning\" OR robotics",
  "OR \"open source\" OR cybersecurity OR biotech OR quantum OR GPU)",
  "lang:en -is:retweet -is:reply"
].join(" ");

export interface DashboardYoutubeChannel {
  name: string;
  handle: string;
  channelId?: string;
}

/** Bounded, high-reach technology roster; every qualifying metric/date is
 * re-read from the video's official player metadata. */
export const DEFAULT_DASHBOARD_YOUTUBE_CHANNELS: readonly DashboardYoutubeChannel[] = [
  { name: "Apple", handle: "Apple", channelId: "UCE_M8A5yxnLfW0KghEeajjw" },
  { name: "MKBHD", handle: "mkbhd", channelId: "UCBJycsmduvYEL83R_U4JriQ" },
  { name: "OpenAI", handle: "OpenAI", channelId: "UCXZCJLdBC09xxGZ6gcdrc6A" },
  { name: "Google", handle: "Google", channelId: "UCK8sQmJBp8GCxrOtXWBpyEA" },
  { name: "NVIDIA", handle: "NVIDIA", channelId: "UCHuiy8bXnmK5nisYHUd1J5g" },
  { name: "Tesla", handle: "Tesla", channelId: "UC5WjFrtBdufl6CZojX3D8dQ" },
  { name: "Linus Tech Tips", handle: "LinusTechTips", channelId: "UCXuqSBlHAE6Xw-yeJA0Tunw" },
  { name: "Mrwhosetheboss", handle: "Mrwhosetheboss", channelId: "UCMiJRAwDNSNzuYeN2uWa0pA" },
  { name: "Fireship", handle: "Fireship", channelId: "UCsBjURrPoezykLs9EqgamOA" },
  { name: "Samsung", handle: "Samsung", channelId: "UCWwgaK7x0_FR1goeSRazfsQ" },
  { name: "Microsoft", handle: "Microsoft", channelId: "UCFtEEv80fQVKkD4h1PF-Xqw" },
  { name: "Android", handle: "Android", channelId: "UC9M7-jzdU8CVrQo1JwmIdWA" },
  { name: "Unbox Therapy", handle: "unboxtherapy", channelId: "UCsTcErHg8oDvUnTzoqsYeNw" },
  { name: "JerryRigEverything", handle: "JerryRigEverything", channelId: "UCWFKCr40YwOZQx8FHU_ZqqQ" },
  { name: "Dave2D", handle: "Dave2D", channelId: "UCVYamHliCI9rw1tHR1xbkfw" },
  { name: "The Verge", handle: "TheVerge", channelId: "UCddiUEpeqJcYeBxX1IVBKvQ" },
  { name: "SpaceX", handle: "SpaceX", channelId: "UCtI0Hodo5o5dUb67FeUjDeA" },
  { name: "Boston Dynamics", handle: "BostonDynamics", channelId: "UC7vVhkEfw4nOGp8TyDk7RcQ" },
  { name: "DJI", handle: "DJI", channelId: "UCsNGtpqGsyw0U6qEG-WHadA" },
  { name: "Nothing", handle: "NothingTechnology", channelId: "UCuVQmkiETvqmLviDcBtQw4A" }
];

interface DashboardRssFeed {
  name: string;
  url: string;
  quality?: number;
  maxItems?: number;
  platform?: "rss" | "research";
  sourceKind?: "article" | "paper";
  independentlyReported?: boolean;
}

export interface ExternalDiscoveryResult {
  candidates: DashboardCandidate[];
  failures: string[];
  sources: string[];
}

export interface ExternalDiscoveryOptions {
  now?: Date;
  fetchImpl?: typeof fetch;
  githubToken?: string | null;
  xBearerToken?: string | null;
  youtubeChannels?: ReadonlyArray<DashboardYoutubeChannel>;
  rssFeeds?: ReadonlyArray<DashboardRssFeed>;
  researchFeeds?: ReadonlyArray<DashboardRssFeed>;
  redditSubreddits?: readonly string[];
}

/**
 * Bounded, public-only Industry discovery. The optional X lane uses only the
 * official recent-search API and native public metrics; no browser sessions,
 * cookies, or authenticated user actions enter this worker.
 */
export async function discoverExternalDashboardCandidates(
  options: ExternalDiscoveryOptions = {}
): Promise<ExternalDiscoveryResult> {
  const now = options.now ?? new Date();
  const fetchImpl = options.fetchImpl ?? fetch;
  const feeds = options.rssFeeds ?? configuredRssFeeds();
  const researchFeeds = options.researchFeeds ?? DEFAULT_DASHBOARD_RESEARCH_FEEDS;
  const subreddits = normalizeSubreddits(options.redditSubreddits ?? DEFAULT_DASHBOARD_REDDIT_SUBREDDITS);
  const githubToken = options.githubToken ?? null;
  const xBearerToken = options.xBearerToken?.trim() || null;
  // The worker may be called with an explicit roster, but it must never turn
  // that input into an unbounded channel/detail crawl. Each retained channel
  // can nominate at most two official player reads below.
  const youtubeChannels = (options.youtubeChannels ?? []).slice(0, MAX_DASHBOARD_YOUTUBE_CHANNELS);
  const youtubeJobs = boundedYoutubeDiscoveryJobs(fetchImpl, now, youtubeChannels);
  const jobs: Array<Promise<{ source: string; candidates: DashboardCandidate[] }>> = [
    fetchHackerNewsCandidates(fetchImpl, now),
    fetchGithubCandidates(fetchImpl, now, githubToken),
    fetchGithubReleaseCandidates(fetchImpl, now, githubToken),
    ...(xBearerToken ? [fetchXRecentSearchCandidates(fetchImpl, now, xBearerToken)] : []),
    ...youtubeJobs,
    ...feeds.map((feed) => fetchRssCandidates(fetchImpl, feed, now)),
    ...researchFeeds.map((feed) => fetchRssCandidates(fetchImpl, feed, now)),
    ...subreddits.map((subreddit) => fetchRedditCandidates(fetchImpl, subreddit, now))
  ];
  const settled = await Promise.allSettled(jobs);
  const candidates: DashboardCandidate[] = [];
  const failures: string[] = [];
  const sources: string[] = [];
  for (const result of settled) {
    if (result.status === "fulfilled") {
      candidates.push(...result.value.candidates);
      sources.push(result.value.source);
    } else {
      // Safe observability label only; do not retain headers, tokens, or raw
      // provider bodies in a public dashboard artifact.
      failures.push(discoveryFailureLabel(result.reason));
    }
  }
  return {
    candidates,
    failures: [...new Set(failures)].sort(),
    sources: [...new Set(sources)].sort()
  };
}

function boundedYoutubeDiscoveryJobs(
  fetchImpl: typeof fetch,
  now: Date,
  channels: readonly DashboardYoutubeChannel[]
): Array<Promise<{ source: string; candidates: DashboardCandidate[] }>> {
  const jobs: Array<Promise<{ source: string; candidates: DashboardCandidate[] }>> = [];
  for (const [index, channel] of channels.entries()) {
    const predecessor = jobs[index - MAX_CONCURRENT_YOUTUBE_CHANNELS];
    const ready = predecessor ? predecessor.then(() => undefined, () => undefined) : Promise.resolve();
    jobs.push(ready.then(() => fetchYoutubeChannelCandidates(fetchImpl, now, channel)));
  }
  return jobs;
}

export async function fetchXRecentSearchCandidates(
  fetchImpl: typeof fetch,
  now: Date,
  bearerToken: string
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const url = new URL(X_RECENT_SEARCH_ENDPOINT);
  url.searchParams.set("query", DEFAULT_DASHBOARD_X_QUERY);
  url.searchParams.set("start_time", new Date(now.getTime() - DASHBOARD_WINDOW_MS).toISOString());
  url.searchParams.set("max_results", String(MAX_X_RECENT_SEARCH_ITEMS));
  url.searchParams.set("sort_order", "relevancy");
  url.searchParams.set("tweet.fields", "author_id,created_at,public_metrics,attachments,lang");
  url.searchParams.set("expansions", "author_id,attachments.media_keys");
  url.searchParams.set("user.fields", "name,username");
  url.searchParams.set("media.fields", "type,url,preview_image_url");
  const response = await fetchImpl(url, {
    headers: {
      Accept: "application/json",
      Authorization: `Bearer ${bearerToken}`,
      "User-Agent": "ReturnerDashboard/1.0 official-x-read-only"
    },
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`x_recent_search_http_${response.status}`);
  const payload = await readBoundedJson<XRecentSearchResponse>(response, "x_recent_search");
  const usersById = new Map((payload.includes?.users ?? []).map((user) => [stableIdentifier(user.id), user]));
  const mediaByKey = new Map((payload.includes?.media ?? []).map((media) => [compactWhitespace(media.media_key), media]));
  const candidates = (payload.data ?? [])
    .slice(0, MAX_X_RECENT_SEARCH_ITEMS)
    .flatMap((post) => xRecentSearchCandidate(post, usersById, mediaByKey, now))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: "x:recent-search", candidates };
}

export async function fetchYoutubeChannelCandidates(
  fetchImpl: typeof fetch,
  now: Date,
  channel: DashboardYoutubeChannel
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const handle = compactWhitespace(channel.handle).replace(/^@/, "");
  if (!/^[A-Za-z0-9._-]{1,100}$/.test(handle)) throw new Error("youtube_invalid_channel_handle");
  const source = `youtube:${sourceSlug(handle)}`;
  const configuredChannelId = compactWhitespace(channel.channelId);
  if (channel.channelId !== undefined && !/^UC[A-Za-z0-9_-]{22}$/.test(configuredChannelId)) {
    throw new Error(`${source.replace(":", "_")}_invalid_channel_id`);
  }
  let queue: YoutubeDiscoveryQueue;
  if (configuredChannelId) {
    try {
      queue = await fetchYoutubeUploadsQueue(fetchImpl, configuredChannelId, source);
    } catch (browseError) {
      try {
        queue = await fetchYoutubeChannelPageQueue(fetchImpl, handle, source);
      } catch {
        throw browseError;
      }
    }
  } else {
    queue = await fetchYoutubeChannelPageQueue(fetchImpl, handle, source);
  }
  const settled = await Promise.allSettled(queue.videoIds.map((videoId) =>
    fetchYoutubeDetailCandidate(fetchImpl, videoId, queue.channelId, channel.name, now, queue.innertubeConfig)
  ));
  const details = settled.flatMap((result) =>
    result.status === "fulfilled" && result.value ? [result.value] : []
  );
  if (details.length === 0) {
    throw new Error(`${source.replace(":", "_")}_detail_unavailable`);
  }
  return {
    source,
    candidates: details.filter((candidate) => isDashboardCandidateEligible(candidate, now))
  };
}

interface YoutubeDiscoveryQueue {
  channelId: string;
  videoIds: string[];
  innertubeConfig: YoutubeInnertubeConfig | null;
}

async function fetchYoutubeUploadsQueue(
  fetchImpl: typeof fetch,
  channelId: string,
  source: string
): Promise<YoutubeDiscoveryQueue> {
  const sourceLabel = `${source.replace(":", "_")}_browse`;
  const browseUrl = new URL("https://www.youtube.com/youtubei/v1/browse");
  browseUrl.searchParams.set("prettyPrint", "false");
  let response: Response;
  try {
    response = await fetchImpl(browseUrl, {
      method: "POST",
      headers: youtubePlayerHeaders(YOUTUBE_WEB_CLIENT_VERSION),
      body: JSON.stringify({
        context: youtubeInnertubeContext(YOUTUBE_WEB_CLIENT_VERSION),
        // Every UC channel has a deterministic UU uploads playlist. The VL
        // prefix asks the official browse endpoint for that playlist directly.
        browseId: `VLUU${channelId.slice(2)}`
      }),
      signal: AbortSignal.timeout(12_000)
    });
  } catch {
    throw new Error(`${sourceLabel}_fetch_failed`);
  }
  if (!response.ok) throw new Error(`${sourceLabel}_http_${response.status}`);
  const payload = await readBoundedJson<unknown>(response, sourceLabel, MAX_YOUTUBE_RESPONSE_BYTES);
  const videoIds = youtubeVideoPreviewIds(payload, MAX_YOUTUBE_DETAIL_CANDIDATES_PER_CHANNEL);
  if (videoIds.length === 0) throw new Error(`${sourceLabel}_no_video_preview_ids`);
  return {
    channelId,
    videoIds,
    innertubeConfig: { apiKey: null, clientVersion: YOUTUBE_WEB_CLIENT_VERSION }
  };
}

async function fetchYoutubeChannelPageQueue(
  fetchImpl: typeof fetch,
  handle: string,
  source: string
): Promise<YoutubeDiscoveryQueue> {
  const channelUrl = new URL(`https://www.youtube.com/@${encodeURIComponent(handle)}/videos`);
  channelUrl.searchParams.set("hl", "en");
  channelUrl.searchParams.set("gl", "US");
  const channelResponse = await fetchImpl(channelUrl, {
    headers: youtubePublicHeaders(),
    signal: AbortSignal.timeout(12_000)
  });
  if (!channelResponse.ok) throw new Error(`${source.replace(":", "_")}_http_${channelResponse.status}`);
  const channelHtml = await readBoundedText(channelResponse, source.replace(":", "_"), MAX_YOUTUBE_RESPONSE_BYTES);
  const channelPage = parseAssignedJson(channelHtml, "ytInitialData");
  if (!channelPage) throw new Error(`${source.replace(":", "_")}_invalid_initial_data`);
  const channelId = youtubeChannelId(channelPage);
  if (!channelId) throw new Error(`${source.replace(":", "_")}_missing_channel_id`);
  const innertubeConfig = youtubeInnertubeConfig(channelHtml);
  // The channel-page counter and relative date are rounded presentation text
  // and differ across YouTube renderer variants. Use the newest renderer IDs
  // only as a bounded detail queue; the public player endpoint supplies the
  // exact identity, publication timestamp, and view count used downstream.
  const videosTab = youtubeSelectedVideosTabContent(channelPage);
  if (!videosTab) throw new Error(`${source.replace(":", "_")}_missing_selected_videos_tab`);
  const videoIds = youtubeVideoPreviewIds(videosTab, MAX_YOUTUBE_DETAIL_CANDIDATES_PER_CHANNEL);
  if (videoIds.length === 0) throw new Error(`${source.replace(":", "_")}_no_video_preview_ids`);
  return { channelId, videoIds, innertubeConfig };
}

interface YoutubeInnertubeConfig {
  apiKey: string | null;
  clientVersion: string;
}

function youtubeInnertubeConfig(channelHtml: string): YoutubeInnertubeConfig | null {
  const apiKey = jsonStringField(channelHtml, "INNERTUBE_API_KEY");
  const clientVersion = jsonStringField(channelHtml, "INNERTUBE_CLIENT_VERSION");
  if (
    !apiKey || !/^AIza[A-Za-z0-9_-]{20,80}$/.test(apiKey) ||
    !clientVersion || !/^\d{1,3}\.\d{8}\.\d{2}\.\d{2}$/.test(clientVersion)
  ) return null;
  return { apiKey, clientVersion };
}

async function fetchYoutubeDetailCandidate(
  fetchImpl: typeof fetch,
  videoId: string,
  expectedChannelId: string,
  rosterName: string,
  observedAt: Date,
  innertubeConfig: YoutubeInnertubeConfig | null
): Promise<DashboardCandidate | null> {
  // The key is public page configuration and is used only for this request.
  // Never include it in a failure label or returned discovery data.
  if (innertubeConfig) {
    try {
      const candidate = await fetchYoutubePlayerCandidate(
        fetchImpl,
        videoId,
        expectedChannelId,
        rosterName,
        observedAt,
        innertubeConfig
      );
      if (candidate) return candidate;
    } catch {
      // A bounded official watch-page read is the compatibility fallback for
      // transient endpoint/config changes. It has the same exact proof gates.
    }
  }
  try {
    return await fetchYoutubeWatchCandidate(fetchImpl, videoId, expectedChannelId, rosterName, observedAt);
  } catch {
    return null;
  }
}

async function fetchYoutubePlayerCandidate(
  fetchImpl: typeof fetch,
  videoId: string,
  expectedChannelId: string,
  rosterName: string,
  observedAt: Date,
  config: YoutubeInnertubeConfig
): Promise<DashboardCandidate | null> {
  const playerUrl = new URL("https://www.youtube.com/youtubei/v1/player");
  if (config.apiKey) playerUrl.searchParams.set("key", config.apiKey);
  playerUrl.searchParams.set("prettyPrint", "false");
  const response = await fetchImpl(playerUrl, {
    method: "POST",
    headers: youtubePlayerHeaders(config.clientVersion),
    body: JSON.stringify({
      context: youtubeInnertubeContext(config.clientVersion),
      videoId,
      contentCheckOk: true,
      racyCheckOk: true
    }),
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`youtube_player_http_${response.status}`);
  const payload = await readBoundedJson<YoutubePlayerResponse>(
    response,
    `youtube_player_${videoId}`,
    MAX_YOUTUBE_PLAYER_RESPONSE_BYTES
  );
  const details = payload.videoDetails;
  const microformat = payload.microformat?.playerMicroformatRenderer;
  const publicationValue = exactYoutubePlayerPublicationValue(microformat);
  return youtubeCandidateFromMetadata({
    videoId,
    expectedChannelId,
    rosterName,
    observedAt,
    nativeVideoId: details?.videoId,
    channelId: details?.channelId,
    author: details?.author,
    title: details?.title,
    description: details?.shortDescription,
    viewCount: details?.viewCount,
    publicationValue,
    likes: null
  });
}

function youtubeInnertubeContext(clientVersion: string): { client: Record<string, string> } {
  return {
    client: {
      clientName: "WEB",
      clientVersion,
      hl: "en",
      gl: "US"
    }
  };
}

async function fetchYoutubeWatchCandidate(
  fetchImpl: typeof fetch,
  videoId: string,
  expectedChannelId: string,
  rosterName: string,
  observedAt: Date
): Promise<DashboardCandidate | null> {
  const watchUrl = new URL("https://www.youtube.com/watch");
  watchUrl.searchParams.set("v", videoId);
  watchUrl.searchParams.set("hl", "en");
  watchUrl.searchParams.set("gl", "US");
  const response = await fetchImpl(watchUrl, {
    headers: youtubePublicHeaders(),
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`youtube_watch_http_${response.status}`);
  const html = await readBoundedText(response, `youtube_watch_${videoId}`, MAX_YOUTUBE_RESPONSE_BYTES);
  const playerResponse = parseAssignedJson(html, "ytInitialPlayerResponse");
  // Prefer the one player-response object associated with this watch page so
  // exact dates from unrelated recommendation payloads cannot attest it.
  const playerMetadata = playerResponse ? JSON.stringify(playerResponse) : html;
  const detailsStart = playerMetadata.indexOf('"videoDetails":{');
  const details = detailsStart >= 0 ? playerMetadata.slice(detailsStart, detailsStart + 160_000) : playerMetadata;
  const publicationValue = exactYoutubePublicationValue(playerMetadata);
  return youtubeCandidateFromMetadata({
    videoId,
    expectedChannelId,
    rosterName,
    observedAt,
    nativeVideoId: jsonStringField(details, "videoId"),
    channelId: jsonStringField(details, "channelId"),
    author: jsonStringField(details, "author"),
    title: jsonStringField(details, "title"),
    description: jsonStringField(details, "shortDescription"),
    viewCount: jsonStringField(details, "viewCount") ?? jsonNumberField(details, "viewCount"),
    publicationValue,
    likes: finiteNonnegative(jsonStringField(html, "likeCount") ?? jsonNumberField(html, "likeCount"))
  });
}

function youtubeCandidateFromMetadata(input: {
  videoId: string;
  expectedChannelId: string;
  rosterName: string;
  observedAt: Date;
  nativeVideoId: unknown;
  channelId: unknown;
  author: unknown;
  title: unknown;
  description: unknown;
  viewCount: unknown;
  publicationValue: string | null;
  likes: number | null;
}): DashboardCandidate | null {
  const nativeVideoId = typeof input.nativeVideoId === "string" ? input.nativeVideoId : "";
  const channelId = typeof input.channelId === "string" ? input.channelId : "";
  const publishedAt = validTimestamp(input.publicationValue);
  const title = compactWhitespace(typeof input.title === "string" ? input.title : "");
  const description = compactWhitespace(typeof input.description === "string" ? input.description : "").slice(0, 4_000);
  const views = youtubeViewCount(input.viewCount);
  if (
    nativeVideoId !== input.videoId || channelId !== input.expectedChannelId || !title || !publishedAt ||
    !isExactYoutubePublicationValue(input.publicationValue) || views === null
  ) return null;
  const authorName = compactWhitespace(typeof input.author === "string" ? input.author : "") || input.rosterName;
  const text = compactWhitespace(`${title} ${description}`);
  const url = `https://www.youtube.com/watch?v=${input.videoId}`;
  return {
    id: `youtube:${input.videoId}`,
    canonicalKey: `youtube:video:${input.videoId}`,
    platform: "youtube",
    sourceKind: "video",
    url,
    title,
    summary: compactSentence(description || title, 300),
    text,
    authorName,
    authorHandle: null,
    publisher: "YouTube",
    publishedAt,
    observedAt: input.observedAt.toISOString(),
    metrics: { views, likes: input.likes },
    entityKeys: [`youtube:channel:${channelId}`],
    topics: xTechnologyTopics(text),
    thumbnailUrl: `https://i.ytimg.com/vi/${input.videoId}/hqdefault.jpg`,
    thumbnailAlt: title,
    independentlyReported: false,
    sourceQuality: 80,
    contentFingerprint: `${input.videoId}:${publishedAt}:${views}:${input.likes ?? ""}:${title}`,
    socialBackfillEligible: true,
    sourceVerified: true,
    sourceLinkStatus: "verified",
    publicationPrecision: "exact"
  };
}

function youtubePublicHeaders(): HeadersInit {
  return {
    Accept: "text/html,application/xhtml+xml",
    "Accept-Language": "en-US,en;q=0.9",
    "User-Agent": "Mozilla/5.0 (compatible; ReturnerDashboard/1.0; +https://github.com/allenbuild/returner-fund)"
  };
}

function youtubePlayerHeaders(clientVersion: string): HeadersInit {
  return {
    Accept: "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "Content-Type": "application/json",
    Origin: "https://www.youtube.com",
    "User-Agent": "Mozilla/5.0 (compatible; ReturnerDashboard/1.0; +https://github.com/allenbuild/returner-fund)",
    "X-YouTube-Client-Name": "1",
    "X-YouTube-Client-Version": clientVersion
  };
}

export async function fetchHackerNewsCandidates(fetchImpl: typeof fetch, now = new Date()): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const after = Math.floor((now.getTime() - DASHBOARD_WINDOW_MS) / 1_000);
  const url = new URL("https://hn.algolia.com/api/v1/search_by_date");
  url.searchParams.set("tags", "story");
  url.searchParams.set("numericFilters", `created_at_i>${after}`);
  url.searchParams.set("hitsPerPage", String(MAX_HN_ITEMS));
  const response = await fetchImpl(url, {
    headers: { Accept: "application/json", "User-Agent": "ReturnerDashboard/1.0 public-read-only" },
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`hacker_news_http_${response.status}`);
  const payload = await readBoundedJson<AlgoliaResponse>(response, "hacker_news");
  const candidates = (payload.hits ?? [])
    .flatMap((hit) => hackerNewsCandidate(hit, now))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: "hacker_news", candidates };
}

export async function fetchGithubCandidates(
  fetchImpl: typeof fetch,
  now = new Date(),
  githubToken: string | null = null
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const after = new Date(now.getTime() - DASHBOARD_WINDOW_MS).toISOString().slice(0, 10);
  const url = new URL("https://api.github.com/search/repositories");
  url.searchParams.set("q", `created:>=${after}`);
  url.searchParams.set("sort", "stars");
  url.searchParams.set("order", "desc");
  url.searchParams.set("per_page", String(MAX_GITHUB_ITEMS));
  const response = await fetchImpl(url, {
    headers: githubPublicHeaders(githubToken),
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`github_http_${response.status}`);
  const payload = await readBoundedJson<GithubSearchResponse>(response, "github");
  const candidates = (payload.items ?? [])
    .flatMap((repository) => githubCandidate(repository, now))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: "github", candidates };
}

/**
 * The public Events endpoint is deliberately a separate bounded job from
 * repository search. A rate limit or transient error on either source cannot
 * suppress the other GitHub discovery lane.
 */
export async function fetchGithubReleaseCandidates(
  fetchImpl: typeof fetch,
  now = new Date(),
  githubToken: string | null = null
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const url = new URL("https://api.github.com/events");
  url.searchParams.set("per_page", String(MAX_GITHUB_EVENT_ITEMS));
  const response = await fetchImpl(url, {
    headers: githubPublicHeaders(githubToken),
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`github_events_http_${response.status}`);
  const payload = await readBoundedJson<unknown>(response, "github_events");
  const events = Array.isArray(payload) ? payload.slice(0, MAX_GITHUB_EVENT_ITEMS) as GithubEvent[] : [];
  const candidates = events
    .flatMap((event) => githubReleaseCandidate(event, now))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: "github_events", candidates };
}

export async function fetchRssCandidates(
  fetchImpl: typeof fetch,
  feed: DashboardRssFeed,
  now = new Date()
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const response = await fetchImpl(feed.url, {
    headers: {
      Accept: "application/atom+xml, application/rss+xml, application/xml, text/xml;q=0.9, text/html;q=0.5",
      "User-Agent": "ReturnerDashboard/1.0 public-read-only"
    },
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`rss_${sourceSlug(feed.name)}_http_${response.status}`);
  const xml = await readBoundedText(response, `rss_${sourceSlug(feed.name)}`);
  const $ = load(xml, { xmlMode: true });
  const sourceItemLimit = feed.sourceKind === "paper" ? MAX_RESEARCH_ITEMS_PER_FEED : MAX_RSS_ITEMS_PER_FEED;
  const maxItems = Number.isFinite(feed.maxItems)
    ? Math.max(1, Math.min(sourceItemLimit, Math.trunc(feed.maxItems ?? sourceItemLimit)))
    : sourceItemLimit;
  const entries = $("item, entry").toArray().slice(0, maxItems);
  const candidates = entries
    .flatMap((entry, index) => rssCandidate($, entry, index, feed))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: `rss:${sourceSlug(feed.name)}`, candidates };
}

export async function fetchRedditCandidates(
  fetchImpl: typeof fetch,
  subreddit: string,
  now = new Date()
): Promise<{ source: string; candidates: DashboardCandidate[] }> {
  const normalizedSubreddit = normalizeSubreddits([subreddit])[0];
  if (!normalizedSubreddit) throw new Error("reddit_invalid_subreddit");
  const url = new URL(`https://www.reddit.com/r/${encodeURIComponent(normalizedSubreddit)}/new.json`);
  url.searchParams.set("limit", String(MAX_REDDIT_ITEMS_PER_SUBREDDIT));
  url.searchParams.set("raw_json", "1");
  const response = await fetchImpl(url, {
    headers: { Accept: "application/json", "User-Agent": "ReturnerDashboard/1.0 public-read-only" },
    signal: AbortSignal.timeout(12_000)
  });
  if (!response.ok) throw new Error(`reddit_${sourceSlug(normalizedSubreddit)}_http_${response.status}`);
  const payload = await readBoundedJson<RedditListing>(response, `reddit_${sourceSlug(normalizedSubreddit)}`);
  const candidates = (payload.data?.children ?? [])
    .flatMap((child) => redditCandidate(child.data, normalizedSubreddit, now))
    .filter((candidate) => isDashboardCandidateEligible(candidate, now));
  return { source: `reddit:${sourceSlug(normalizedSubreddit)}`, candidates };
}

function hackerNewsCandidate(hit: AlgoliaHit, observedAt: Date): DashboardCandidate[] {
  const title = compactWhitespace(hit.title ?? hit.story_title);
  const storyText = compactSentence(hit.story_text, 300);
  const publishedAt = validTimestamp(hit.created_at);
  const id = compactWhitespace(hit.objectID);
  const upvotes = finiteNonnegative(hit.points);
  const comments = finiteNonnegative(hit.num_comments);
  if (
    !title ||
    !publishedAt ||
    !id ||
    !isTechnologyEditorialArticle(title, storyText) ||
    (upvotes ?? 0) < MIN_HN_UPVOTES && (comments ?? 0) < MIN_HN_COMMENTS
  ) return [];
  const nativeUrl = `https://news.ycombinator.com/item?id=${encodeURIComponent(id)}`;
  const destinationUrl = canonicalDashboardUrl(hit.url ?? hit.story_url);
  return [{
    id: `hn:${id}`,
    canonicalKey: `hacker_news:post:${id}`,
    platform: "hacker_news",
    sourceKind: "discussion",
    url: nativeUrl,
    destinationUrl,
    linkedUrls: destinationUrl ? [destinationUrl] : [],
    title,
    summary: storyText,
    text: storyText,
    authorName: compactWhitespace(hit.author) || null,
    publisher: "Hacker News",
    publishedAt,
    observedAt: observedAt.toISOString(),
    metrics: { upvotes, comments },
    entityKeys: destinationUrl ? [`destination:${destinationUrl}`] : [],
    topics: [],
    independentlyReported: true,
    sourceQuality: 70,
    contentFingerprint: `${id}:${title}`
  }];
}

function githubCandidate(repository: GithubRepository, observedAt: Date): DashboardCandidate[] {
  const url = canonicalDashboardUrl(repository.html_url);
  const publishedAt = validTimestamp(repository.created_at);
  const id = String(repository.id ?? "").trim();
  const name = compactWhitespace(repository.full_name || repository.name);
  if (!url || !publishedAt || !id || !name) return [];
  const description = compactWhitespace(repository.description);
  const stars = finiteNonnegative(repository.stargazers_count);
  if (!isTechnologyRepositoryCandidate(name, description, stars)) return [];
  return [{
    id: `github:${id}`,
    canonicalKey: `github:repository-object:${id}`,
    platform: "github",
    sourceKind: "repository",
    url,
    destinationUrl: url,
    linkedUrls: [url],
    title: name,
    summary: description || null,
    text: description || null,
    authorName: compactWhitespace(repository.owner?.login) || null,
    publisher: "GitHub",
    publishedAt,
    observedAt: observedAt.toISOString(),
    metrics: {
      stars,
      forks: finiteNonnegative(repository.forks_count),
      watchers: finiteNonnegative(repository.watchers_count)
    },
    entityKeys: [`repository:${id}`, `destination:${url}`],
    entityLabel: name,
    topics: [],
    thumbnailUrl: repository.owner?.avatar_url ?? null,
    thumbnailAlt: `${name} repository preview`,
    independentlyReported: false,
    sourceQuality: 72,
    contentFingerprint: `${id}:${repository.updated_at ?? ""}:${description}`
  }];
}

function isTechnologyRepositoryCandidate(name: string, description: string, stars: number | null): boolean {
  // A freshly-created repository with no meaningful description is usually
  // not enough evidence for a public technology-news card. Require an
  // explicit technical purpose, and exclude speculative-token spam entirely.
  // Repository owners frequently have generic terms such as "developer" in
  // their handle. Score the actual project name and its description instead,
  // so an unrelated repository cannot enter merely through its namespace.
  const projectName = compactWhitespace(name.split("/").at(-1));
  const text = compactWhitespace(`${projectName} ${description}`);
  return description.length >= 16 &&
    (stars ?? 0) >= MIN_GITHUB_STARS &&
    CORE_TECHNOLOGY_SIGNAL.test(text) &&
    !LOW_SIGNAL_OR_PROMOTIONAL_REPOSITORY.test(text);
}

function githubReleaseCandidate(event: GithubEvent, observedAt: Date): DashboardCandidate[] {
  const release = event.payload?.release;
  const action = compactWhitespace(event.payload?.action).toLowerCase();
  if (event.type !== "ReleaseEvent" || action !== "published" || !release || release.draft === true) return [];

  const eventId = stableIdentifier(event.id);
  const releaseId = stableIdentifier(release?.id);
  const repositoryId = stableIdentifier(event.repo?.id);
  const repositoryName = compactWhitespace(event.repo?.name);
  const url = canonicalDashboardUrl(release?.html_url);
  const publishedAt = validTimestamp(release?.published_at ?? event.created_at);
  if (!eventId || !releaseId || !repositoryName || !url || !publishedAt) return [];

  const releaseName = compactWhitespace(release.name) || compactWhitespace(release.tag_name);
  const title = releaseName
    ? `${repositoryName} releases ${releaseName}`
    : `${repositoryName} publishes a release`;
  const description = compactSentence(release.body, 300);
  if (LOW_SIGNAL_OR_PROMOTIONAL_REPOSITORY.test(`${repositoryName} ${releaseName} ${description ?? ""}`)) return [];
  const downloads = Array.isArray(release.assets)
    ? release.assets.reduce((total, asset) => total + (finiteNonnegative(asset.download_count) ?? 0), 0)
    : 0;
  const reactions = finiteNonnegative(release.reactions?.total_count);

  return [{
    id: `github:release:${releaseId}`,
    canonicalKey: `github:release:${releaseId}`,
    platform: "github",
    sourceKind: "release",
    url,
    destinationUrl: url,
    linkedUrls: [url],
    title,
    summary: description,
    text: description,
    authorName: compactWhitespace(release.author?.login) || compactWhitespace(event.actor?.login) || null,
    publisher: "GitHub",
    publishedAt,
    observedAt: observedAt.toISOString(),
    metrics: { downloads, reactions },
    entityKeys: [
      ...(repositoryId ? [`repository:${repositoryId}`] : []),
      `destination:${url}`
    ],
    entityLabel: repositoryName,
    topics: ["open_source"],
    thumbnailUrl: null,
    thumbnailAlt: `${title} release preview`,
    independentlyReported: false,
    sourceQuality: 74,
    contentFingerprint: `${eventId}:${releaseId}:${release.updated_at ?? release.published_at ?? ""}:${downloads}:${reactions ?? ""}:${description ?? ""}`
  }];
}

function githubPublicHeaders(githubToken: string | null): HeadersInit {
  return {
    Accept: "application/vnd.github+json",
    "User-Agent": "ReturnerDashboard/1.0 public-read-only",
    "X-GitHub-Api-Version": "2022-11-28",
    ...(githubToken ? { Authorization: `Bearer ${githubToken}` } : {})
  };
}

function stableIdentifier(value: unknown): string {
  return typeof value === "string" || typeof value === "number" ? String(value).trim() : "";
}

function rssCandidate(
  $: ReturnType<typeof load>,
  entry: Parameters<ReturnType<typeof load>>[0],
  index: number,
  feed: DashboardRssFeed
): DashboardCandidate[] {
  const node = $(entry);
  const title = compactWhitespace(node.find("title").first().text());
  const url = canonicalDashboardUrl(
    node.find("link[rel='alternate']").first().attr("href") ||
    node.find("link").first().attr("href") ||
    node.find("link").first().text()
  );
  const publishedAtRaw = compactWhitespace(
    node.find("published, pubDate, updated, dc\\:date").first().text()
  );
  const publishedAt = validTimestamp(publishedAtRaw);
  if (!title || !url || !publishedAt) return [];
  const description = rssEntrySummary(node.find("description, summary, content, content\\:encoded").first().text());
  const sourceKind = feed.sourceKind ?? "article";
  if (sourceKind === "article" && !isTechnologyEditorialArticle(title, description)) return [];
  const thumbnailUrl = rssThumbnailUrl($, entry);
  const articleKey = compactWhitespace(node.find("guid, id").first().text()) || url;
  return [{
    id: `rss:${sourceSlug(feed.name)}:${stableHash(articleKey)}`,
    canonicalKey: `rss:url:${url}`,
    platform: feed.platform ?? "rss",
    sourceKind,
    url,
    destinationUrl: url,
    linkedUrls: [url],
    title,
    summary: description,
    text: description,
    publisher: feed.name,
    publishedAt,
    observedAt: publishedAt,
    metrics: {},
    entityKeys: [`destination:${url}`],
    topics: sourceKind === "paper" ? ["research"] : [],
    thumbnailUrl,
    thumbnailAlt: title,
    independentlyReported: feed.independentlyReported ?? true,
    sourceQuality: feed.quality ?? 62,
    contentFingerprint: `${articleKey}:${title}:${index}`,
    // This row came directly from a fetched, allowlisted publisher/research
    // feed with a canonical public link. Timestamp precision is asserted only
    // when the source supplied both a clock and an explicit timezone.
    sourceVerified: true,
    sourceLinkStatus: "verified",
    publicationPrecision: rssPublicationPrecision(publishedAtRaw)
  }];
}

function rssPublicationPrecision(value: string): "exact" | "day" | "unknown" {
  if (!value) return "unknown";
  const hasClock = /(?:T|\s)\d{1,2}:\d{2}(?::\d{2}(?:\.\d+)?)?/i.test(value);
  const hasTimezone = /(?:Z|GMT|UTC|UT|[+-]\d{2}:?\d{2})\s*$/i.test(value);
  if (hasClock && hasTimezone) return "exact";
  return /\b\d{4}[-/]\d{1,2}[-/]\d{1,2}\b|\b\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}\b/.test(value)
    ? "day"
    : "unknown";
}

/** RSS descriptions frequently arrive as CDATA-wrapped HTML. Keep markup out
 * of relevance scoring and the public summary while leaving the raw fragment
 * available to the separate thumbnail extractor below. */
function rssEntryPlainText(value: string | null | undefined): string | null {
  const raw = compactWhitespace(value);
  if (!raw) return null;
  const plainText = !/<[a-z][^>]*>/i.test(raw) ? raw : compactWhitespace(load(raw).text());
  return stripRssPublisherBoilerplate(plainText) || null;
}

function rssEntrySummary(value: string | null | undefined): string | null {
  const summary = compactSentence(rssEntryPlainText(value), 300);
  if (!summary) return null;
  const wordCount = summary.match(/[\p{L}\p{N}]+/gu)?.length ?? 0;
  // A fragment such as "Flamingo missiles were used." contains no useful
  // story context. Let the pipeline use the factual title instead of
  // publishing a clipped, context-free RSS excerpt.
  if (wordCount < MIN_RSS_SUMMARY_WORDS) return null;
  return summary;
}

function stripRssPublisherBoilerplate(value: string | null | undefined): string {
  return compactWhitespace(value).replace(RSS_PUBLISHER_BOILERPLATE, "").replace(/\s+([.,;:!?])/g, "$1").trim();
}

function isTechnologyEditorialArticle(
  title: string,
  description: string | null
): boolean {
  const headline = stripRssPublisherBoilerplate(title);
  const context = compactWhitespace([headline, stripRssPublisherBoilerplate(description)].filter(Boolean).join(" "));
  const hasTitleLedTechnologySignal =
    CORE_TECHNOLOGY_SIGNAL.test(headline) ||
    APPLIED_TECHNOLOGY_TITLE_SIGNAL.test(headline) && CORE_TECHNOLOGY_SIGNAL.test(context);
  return Boolean(headline) &&
    hasTitleLedTechnologySignal &&
    !COMMERCE_PROMOTION_FORMAT.test(context) &&
    !LOWER_VALUE_EDITORIAL_FORMAT.test(context) &&
    !OPINION_OR_VAGUE_FORMAT.test(context) &&
    !ENTERTAINMENT_OR_LIFESTYLE_SIGNAL.test(context) &&
    !GEOPOLITICAL_OR_MILITARY_SIGNAL.test(context);
}

/**
 * Publisher feeds commonly put their card image in `media:*`, but WordPress,
 * Atom, and newspaper feeds also frequently encode it inside a bounded entry
 * HTML fragment. We only extract an absolute public HTTPS URL; no image is
 * fetched here, and the dashboard's separate thumbnail policy still decides
 * whether the renderer may request the host.
 */
function rssThumbnailUrl(
  $: ReturnType<typeof load>,
  entry: Parameters<ReturnType<typeof load>>[0]
): string | null {
  const node = $(entry);
  const directMedia = node
    .find("media\\:thumbnail, media\\:content[type^='image'], media\\:content[medium='image'], enclosure[type^='image'], media\\:content")
    .toArray();
  for (const media of directMedia) {
    const thumbnail = absolutePublicHttpsUrl($(media).attr("url"));
    if (thumbnail) return thumbnail;
  }

  const htmlFragments = node
    .find("description, summary, content, content\\:encoded")
    .toArray()
    .map((content) => $(content).text().slice(0, MAX_ENTRY_IMAGE_HTML_CHARS));
  for (const html of htmlFragments) {
    const thumbnail = firstHtmlImageUrl(html);
    if (thumbnail) return thumbnail;
  }
  return null;
}

function firstHtmlImageUrl(html: string): string | null {
  if (!html.trim()) return null;
  const fragment = load(html);
  for (const image of fragment("img").toArray()) {
    const node = fragment(image);
    for (const attribute of ["src", "data-src", "data-original", "data-lazy-src"]) {
      const thumbnail = absolutePublicHttpsUrl(node.attr(attribute));
      if (thumbnail) return thumbnail;
    }
  }
  return null;
}

function absolutePublicHttpsUrl(value: string | null | undefined): string | null {
  const raw = compactWhitespace(value);
  if (!raw) return null;
  try {
    const parsed = new URL(raw);
    if (
      parsed.protocol !== "https:" ||
      Boolean(parsed.port || parsed.username || parsed.password) ||
      !isPublicRssHost(parsed.hostname)
    ) {
      return null;
    }
    return canonicalDashboardUrl(parsed.toString());
  } catch {
    return null;
  }
}

function redditCandidate(post: RedditPost | undefined, subreddit: string, observedAt: Date): DashboardCandidate[] {
  const id = compactWhitespace(post?.id);
  const title = compactWhitespace(post?.title);
  const permalink = compactWhitespace(post?.permalink);
  const timestamp = typeof post?.created_utc === "number" ? post.created_utc * 1_000 : Number.NaN;
  const publishedDate = new Date(timestamp);
  const publishedAt = Number.isFinite(publishedDate.getTime()) ? publishedDate.toISOString() : null;
  if (!id || !title || !permalink || !publishedAt) return [];
  const nativeUrl = canonicalDashboardUrl(`https://www.reddit.com${permalink}`);
  if (!nativeUrl) return [];
  const submittedUrl = canonicalDashboardUrl(post?.url ?? null);
  const destinationUrl = submittedUrl && !isRedditUrl(submittedUrl) ? submittedUrl : null;
  const description = compactSentence(post?.selftext, 300);
  if (!isTechnologyEditorialArticle(title, description)) return [];
  return [{
    id: `reddit:${subreddit}:${id}`,
    canonicalKey: `reddit:post:${id}`,
    platform: "reddit",
    sourceKind: "discussion",
    url: nativeUrl,
    destinationUrl,
    linkedUrls: destinationUrl ? [destinationUrl] : [],
    title,
    summary: description,
    text: description,
    authorName: compactWhitespace(post?.author) || null,
    publisher: `r/${subreddit}`,
    publishedAt,
    observedAt: observedAt.toISOString(),
    metrics: { upvotes: finiteNonnegative(post?.score), comments: finiteNonnegative(post?.num_comments) },
    entityKeys: destinationUrl ? [`destination:${destinationUrl}`] : [],
    topics: [],
    // A public subreddit listing does not establish whether the submitter is
    // independent. It can contribute attention, but never a confirmation
    // bonus without a verified adapter making that determination.
    independentlyReported: false,
    sourceQuality: 58,
    contentFingerprint: `${id}:${post?.score ?? ""}:${post?.num_comments ?? ""}:${title}`
  }];
}

function xRecentSearchCandidate(
  post: XRecentPost,
  usersById: ReadonlyMap<string, XRecentUser>,
  mediaByKey: ReadonlyMap<string, XRecentMedia>,
  observedAt: Date
): DashboardCandidate[] {
  const id = stableIdentifier(post.id);
  const author = usersById.get(stableIdentifier(post.author_id));
  const authorHandle = compactWhitespace(author?.username).replace(/^@/, "");
  const publishedAt = validTimestamp(post.created_at);
  const text = compactWhitespace(post.text);
  if (!id || !/^\d+$/.test(id) || !/^[A-Za-z0-9_]{1,15}$/.test(authorHandle) || !publishedAt || !text) return [];

  const url = canonicalDashboardUrl(`https://x.com/${authorHandle}/status/${id}`);
  if (!url) return [];
  const metrics = {
    views: finiteNonnegative(post.public_metrics?.impression_count),
    likes: finiteNonnegative(post.public_metrics?.like_count),
    replies: finiteNonnegative(post.public_metrics?.reply_count),
    reposts: finiteNonnegative(post.public_metrics?.retweet_count),
    quotes: finiteNonnegative(post.public_metrics?.quote_count)
  };
  const media = (post.attachments?.media_keys ?? [])
    .map((key) => mediaByKey.get(compactWhitespace(key)))
    .find(Boolean);
  const thumbnailUrl = canonicalDashboardUrl(media?.preview_image_url ?? media?.url);
  const title = compactSentence(text, 160) ?? text.slice(0, 160);

  return [{
    id: `x:${id}`,
    canonicalKey: `x:post:${id}`,
    platform: "x",
    sourceKind: media?.type === "video" || media?.type === "animated_gif" ? "video" : "post",
    url,
    title,
    summary: compactSentence(text, 300),
    text,
    authorName: compactWhitespace(author?.name) || authorHandle,
    authorHandle,
    publisher: "X",
    publishedAt,
    observedAt: observedAt.toISOString(),
    metrics,
    entityKeys: [`x:author:${authorHandle.toLowerCase()}`],
    topics: xTechnologyTopics(text),
    thumbnailUrl,
    thumbnailAlt: thumbnailUrl ? `${authorHandle} post media` : null,
    independentlyReported: false,
    sourceQuality: 76,
    contentFingerprint: `${id}:${publishedAt}:${metrics.views ?? ""}:${metrics.likes ?? ""}:${text}`,
    // These proofs come from one official X response: the expanded author
    // establishes the canonical link, `created_at` is exact, and
    // `impression_count` is the native view counter used by the hard gate.
    socialBackfillEligible: true,
    sourceVerified: true,
    sourceLinkStatus: "verified",
    publicationPrecision: "exact"
  }];
}

function xTechnologyTopics(text: string): DashboardCandidate["topics"] {
  const topics = new Set<NonNullable<DashboardCandidate["topics"]>[number]>();
  if (/\b(?:ai|a\.i\.|artificial intelligence|machine learning|llm|chatgpt|claude|gemini|nvidia|gpu)\b/i.test(text)) topics.add("ai");
  if (/\brobot(?:ics)?\b/i.test(text)) topics.add("robotics");
  if (/\b(?:biotech|bioengineering|genomics?|medical device|healthtech)\b/i.test(text)) topics.add("biotech");
  if (/\bopen[ -]?source\b/i.test(text)) topics.add("open_source");
  if (/\b(?:research|paper|study|benchmark)\b/i.test(text)) topics.add("research");
  if (/\b(?:launch|release|ship|introduc(?:e|ing)|announce)\b/i.test(text)) topics.add("launches");
  if (/\b(?:funding|raise[ds]?|series [a-z]|seed round)\b/i.test(text)) topics.add("funding");
  if (/\bstartup\b/i.test(text)) topics.add("startups");
  return [...topics];
}

function youtubeVideoPreviewIds(root: unknown, limit: number): string[] {
  const result: string[] = [];
  const seen = new Set<string>();
  for (const value of objectGraph(root)) {
    for (const videoId of youtubeVideoIdsFromRendererRecord(value)) {
      if (seen.has(videoId)) continue;
      seen.add(videoId);
      result.push(videoId);
      if (result.length >= limit) return result;
    }
  }
  return result;
}

function youtubeSelectedVideosTabContent(root: unknown): unknown | null {
  for (const value of objectGraph(root)) {
    const tab = objectValue(value.tabRenderer);
    if (tab?.selected !== true || !tab.content) continue;
    const title = youtubeText(tab.title).toLowerCase();
    const endpoint = objectValue(tab.endpoint);
    const commandMetadata = objectValue(endpoint?.commandMetadata);
    const webCommandMetadata = objectValue(commandMetadata?.webCommandMetadata);
    const endpointPath = typeof webCommandMetadata?.url === "string" ? webCommandMetadata.url : "";
    if (title === "videos" || /\/videos(?:[?#]|$)/i.test(endpointPath)) return tab.content;
  }
  return null;
}

function youtubeText(value: unknown): string {
  if (typeof value === "string") return compactWhitespace(value);
  const record = objectValue(value);
  if (!record) return "";
  if (typeof record.simpleText === "string") return compactWhitespace(record.simpleText);
  if (typeof record.content === "string") return compactWhitespace(record.content);
  if (!Array.isArray(record.runs)) return "";
  return compactWhitespace(record.runs.flatMap((run) => {
    const text = objectValue(run)?.text;
    return typeof text === "string" ? [text] : [];
  }).join(" "));
}

function youtubeVideoIdsFromRendererRecord(value: Record<string, unknown>): string[] {
  const ids: string[] = [];
  const lockup = objectValue(value.lockupViewModel);
  if (lockup?.contentType === "LOCKUP_CONTENT_TYPE_VIDEO") {
    ids.push(youtubeVideoId(lockup.contentId));
  }
  ids.push(
    youtubeVideoId(objectValue(value.videoRenderer)?.videoId),
    youtubeVideoId(objectValue(value.gridVideoRenderer)?.videoId),
    youtubeVideoId(objectValue(value.playlistVideoRenderer)?.videoId)
  );

  // Some rich-grid payloads keep the renderer under `richItemRenderer.content`
  // instead of exposing it as a sibling visited by older traversal code.
  const richContent = objectValue(objectValue(value.richItemRenderer)?.content);
  const richLockup = objectValue(richContent?.lockupViewModel);
  if (richLockup?.contentType === "LOCKUP_CONTENT_TYPE_VIDEO") {
    ids.push(youtubeVideoId(richLockup.contentId));
  }
  ids.push(
    youtubeVideoId(objectValue(richContent?.videoRenderer)?.videoId),
    youtubeVideoId(objectValue(richContent?.gridVideoRenderer)?.videoId),
    youtubeVideoId(objectValue(richContent?.playlistVideoRenderer)?.videoId)
  );
  return ids.filter(Boolean);
}

function youtubeVideoId(value: unknown): string {
  return typeof value === "string" && /^[A-Za-z0-9_-]{11}$/.test(value) ? value : "";
}

function objectValue(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function youtubeChannelId(root: unknown): string | null {
  for (const value of objectGraph(root)) {
    const metadata = value.channelMetadataRenderer;
    const rawExternalId = metadata && typeof metadata === "object"
      ? (metadata as { externalId?: unknown }).externalId
      : null;
    const externalId = typeof rawExternalId === "string" ? compactWhitespace(rawExternalId) : "";
    if (/^UC[A-Za-z0-9_-]{20,}$/.test(externalId)) return externalId;
  }
  return null;
}

function objectGraph(root: unknown): Array<Record<string, unknown>> {
  const result: Array<Record<string, unknown>> = [];
  const stack: unknown[] = [root];
  while (stack.length > 0 && result.length < 100_000) {
    const value = stack.pop();
    if (!value || typeof value !== "object") continue;
    if (Array.isArray(value)) {
      // Push in reverse so the LIFO traversal observes channel renderers in
      // their displayed newest-first order.
      for (let index = value.length - 1; index >= 0; index -= 1) stack.push(value[index]);
      continue;
    }
    const record = value as Record<string, unknown>;
    result.push(record);
    const children = Object.values(record);
    for (let index = children.length - 1; index >= 0; index -= 1) stack.push(children[index]);
  }
  return result;
}

function parseAssignedJson(html: string, variableName: string): unknown | null {
  for (const marker of [`var ${variableName} = `, `${variableName} = `]) {
    const markerIndex = html.indexOf(marker);
    if (markerIndex < 0) continue;
    const start = html.indexOf("{", markerIndex + marker.length);
    if (start < 0) continue;
    let depth = 0;
    let quoted = false;
    let escaped = false;
    for (let index = start; index < html.length; index += 1) {
      const character = html[index];
      if (quoted) {
        if (escaped) escaped = false;
        else if (character === "\\") escaped = true;
        else if (character === '"') quoted = false;
        continue;
      }
      if (character === '"') quoted = true;
      else if (character === "{") depth += 1;
      else if (character === "}" && --depth === 0) {
        try {
          return JSON.parse(html.slice(start, index + 1));
        } catch {
          break;
        }
      }
    }
  }
  return null;
}

function jsonStringField(value: string, field: string): string | null {
  const match = value.match(new RegExp(`"${field}":"((?:\\\\.|[^"\\\\])*)"`));
  if (!match) return null;
  try {
    return JSON.parse(`"${match[1]}"`) as string;
  } catch {
    return null;
  }
}

function jsonNumberField(value: string, field: string): string | null {
  return value.match(new RegExp(`"${field}":(\\d+)`))?.[1] ?? null;
}

function exactYoutubePublicationValue(value: string): string | null {
  for (const field of ["publishDate", "uploadDate"]) {
    const matches = value.matchAll(new RegExp(`"${field}":"((?:\\\\.|[^"\\\\])*)"`, "g"));
    for (const match of matches) {
      try {
        const decoded = JSON.parse(`"${match[1]}"`) as string;
        if (isExactYoutubePublicationValue(decoded) && validTimestamp(decoded)) return decoded;
      } catch {
        // Keep scanning bounded official metadata for another exact value.
      }
    }
  }
  return null;
}

function exactYoutubePlayerPublicationValue(renderer: YoutubePlayerMicroformatRenderer | null | undefined): string | null {
  if (!renderer) return null;
  for (const value of [renderer.publishDate, renderer.uploadDate]) {
    if (typeof value === "string" && isExactYoutubePublicationValue(value) && validTimestamp(value)) return value;
  }
  return null;
}

function isExactYoutubePublicationValue(value: string | null): boolean {
  return Boolean(value && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/i.test(value));
}

function youtubeViewCount(value: unknown): number | null {
  const text = typeof value === "number" && Number.isSafeInteger(value)
    ? String(value)
    : typeof value === "string" ? value : "";
  if (!/^\d+$/.test(text)) return null;
  const count = Number(text);
  return Number.isSafeInteger(count) && count >= 0 ? count : null;
}

function configuredRssFeeds(): ReadonlyArray<DashboardRssFeed> {
  const configured = process.env.DASHBOARD_RSS_FEEDS?.trim();
  if (!configured) return DEFAULT_DASHBOARD_RSS_FEEDS;
  // Runtime configuration can choose a feed path only on the fixed,
  // built-in publication hosts; no arbitrary scheme, credentials, or host is
  // accepted.
  return configured.split(",").flatMap((raw, index) => {
    const url = configuredRssUrl(raw);
    if (!url) return [];
    return [{ name: `Configured feed ${index + 1}`, url, quality: 62 }];
  }).slice(0, 8);
}

function configuredRssUrl(value: string): string | null {
  try {
    const parsed = new URL(value.trim());
    const hostname = normalizedRssHostname(parsed.hostname);
    if (
      parsed.protocol !== "https:" ||
      Boolean(parsed.port) ||
      Boolean(parsed.username || parsed.password) ||
      !isPublicRssHost(hostname) ||
      !CONFIGURED_RSS_HOST_ALLOWLIST.has(hostname)
    ) {
      return null;
    }
    return canonicalDashboardUrl(parsed.toString());
  } catch {
    return null;
  }
}

function isPublicRssHost(hostname: string): boolean {
  const host = normalizedRssHostname(hostname);
  if (!host || host === "localhost" || host.endsWith(".localhost")) return false;
  const version = isIP(host);
  if (version === 4) return !isPrivateIpv4(host);
  if (version === 6) return !isPrivateIpv6(host);
  return true;
}

function normalizedRssHostname(hostname: string): string {
  return hostname.replace(/^\[|\]$/g, "").toLowerCase().replace(/\.$/, "");
}

function isPrivateIpv4(host: string): boolean {
  const [first, second] = host.split(".").map(Number);
  return first === 0 ||
    first === 10 ||
    first === 127 ||
    (first === 169 && second === 254) ||
    (first === 172 && second >= 16 && second <= 31) ||
    (first === 192 && second === 168);
}

function isPrivateIpv6(host: string): boolean {
  // `URL` normalizes IPv4-mapped addresses (for example, 127.0.0.1 becomes
  // ::ffff:7f00:1), so reject the reserved/compatibility `::/` range rather
  // than attempting to recover an embedded IPv4 string.
  if (host.startsWith("::")) return true;
  const firstSegment = Number.parseInt(host.split(":")[0] || "0", 16);
  // fc00::/7 private use and fe80::/10 link-local addresses are never valid
  // configured feed targets.
  return (firstSegment & 0xfe00) === 0xfc00 || (firstSegment & 0xffc0) === 0xfe80;
}

function normalizeSubreddits(values: readonly string[]): string[] {
  return [...new Set(values
    .map((value) => value.trim())
    .filter((value) => /^[A-Za-z0-9_]{2,30}$/.test(value)))]
    .slice(0, 8);
}

function isRedditUrl(value: string): boolean {
  try {
    return new URL(value).hostname.endsWith("reddit.com");
  } catch {
    return false;
  }
}

async function readBoundedJson<T>(response: Response, source: string, maxResponseBytes = MAX_RESPONSE_BYTES): Promise<T> {
  const text = await readBoundedText(response, source, maxResponseBytes);
  try {
    return JSON.parse(text) as T;
  } catch {
    throw new Error(`${source}_invalid_json`);
  }
}

async function readBoundedText(response: Response, source: string, maxResponseBytes = MAX_RESPONSE_BYTES): Promise<string> {
  const contentLength = Number(response.headers.get("content-length") ?? "0");
  if (Number.isFinite(contentLength) && contentLength > maxResponseBytes) {
    throw new Error(`${source}_response_too_large`);
  }
  if (!response.body) return "";
  const reader = response.body.getReader();
  const chunks: Uint8Array[] = [];
  let size = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      size += value.byteLength;
      if (size > maxResponseBytes) {
        await reader.cancel();
        throw new Error(`${source}_response_too_large`);
      }
      chunks.push(value);
    }
  } finally {
    reader.releaseLock();
  }
  return new TextDecoder().decode(concatenate(chunks, size));
}

function concatenate(chunks: Uint8Array[], size: number): Uint8Array {
  const output = new Uint8Array(size);
  let offset = 0;
  for (const chunk of chunks) {
    output.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return output;
}

function validTimestamp(value: unknown): string | null {
  const date = typeof value === "string" ? safeDate(value) : null;
  return date?.toISOString() ?? null;
}

function finiteNonnegative(value: unknown): number | null {
  const number = typeof value === "number" ? value : Number(value);
  return Number.isFinite(number) && number >= 0 ? number : null;
}

function sourceSlug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "source";
}

function discoveryFailureLabel(error: unknown): string {
  const raw = error instanceof Error ? error.message : "unknown";
  return raw.replace(/[^a-z0-9_.:-]+/gi, "_").slice(0, 160) || "unknown";
}

interface AlgoliaResponse { hits?: AlgoliaHit[] }
interface AlgoliaHit {
  objectID?: string;
  title?: string | null;
  story_title?: string | null;
  story_text?: string | null;
  url?: string | null;
  story_url?: string | null;
  author?: string | null;
  created_at?: string | null;
  points?: number | null;
  num_comments?: number | null;
}
interface GithubSearchResponse { items?: GithubRepository[] }
interface GithubRepository {
  id?: number | string;
  name?: string | null;
  full_name?: string | null;
  html_url?: string | null;
  description?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  stargazers_count?: number | null;
  forks_count?: number | null;
  watchers_count?: number | null;
  owner?: { login?: string | null; avatar_url?: string | null } | null;
}
interface GithubEvent {
  id?: string | number;
  type?: string | null;
  created_at?: string | null;
  actor?: { login?: string | null } | null;
  repo?: { id?: string | number; name?: string | null } | null;
  payload?: {
    action?: string | null;
    release?: GithubRelease | null;
  } | null;
}
interface GithubRelease {
  id?: string | number;
  name?: string | null;
  tag_name?: string | null;
  html_url?: string | null;
  body?: string | null;
  published_at?: string | null;
  updated_at?: string | null;
  draft?: boolean | null;
  author?: { login?: string | null } | null;
  reactions?: { total_count?: number | null } | null;
  assets?: Array<{ download_count?: number | null }> | null;
}
interface RedditListing {
  data?: { children?: Array<{ data?: RedditPost }> };
}
interface RedditPost {
  id?: string | null;
  title?: string | null;
  permalink?: string | null;
  url?: string | null;
  selftext?: string | null;
  author?: string | null;
  created_utc?: number | null;
  score?: number | null;
  num_comments?: number | null;
}
interface XRecentSearchResponse {
  data?: XRecentPost[];
  includes?: { users?: XRecentUser[]; media?: XRecentMedia[] };
}
interface XRecentPost {
  id?: string | number | null;
  author_id?: string | number | null;
  text?: string | null;
  created_at?: string | null;
  lang?: string | null;
  public_metrics?: {
    impression_count?: number | null;
    like_count?: number | null;
    reply_count?: number | null;
    retweet_count?: number | null;
    quote_count?: number | null;
  } | null;
  attachments?: { media_keys?: string[] | null } | null;
}
interface XRecentUser {
  id?: string | number | null;
  name?: string | null;
  username?: string | null;
}
interface XRecentMedia {
  media_key?: string | null;
  type?: string | null;
  url?: string | null;
  preview_image_url?: string | null;
}
interface YoutubePlayerMicroformatRenderer {
  publishDate?: unknown;
  uploadDate?: unknown;
}
interface YoutubePlayerResponse {
  videoDetails?: {
    videoId?: unknown;
    channelId?: unknown;
    author?: unknown;
    title?: unknown;
    shortDescription?: unknown;
    viewCount?: unknown;
  } | null;
  microformat?: {
    playerMicroformatRenderer?: YoutubePlayerMicroformatRenderer | null;
  } | null;
}
